---
title: "ERS-debt"
author: "Britta Schumacher"
date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: yeti
    toc: yes
    toc_float: true
    code_folding: hide
---

Data from: https://www.ers.usda.gov/data-products/farm-income-and-wealth-statistics/data-files-us-and-state-level-farm-income-and-wealth-statistics/
Other: https://www.ers.usda.gov/data-products/farm-income-and-wealth-statistics/charts-and-maps-of-us-farm-balance-sheet-data/; https://www.fb.org/market-intel/who-holds-farm-debt

```{r warning = F, message = F}
library(tidyverse)
library(knitr)
library(viridis)
w <- read.csv("./data/ers-wealthstatdata.csv")
w <- w[c(1,2,4:8,11)]

debt <- w %>% 
  filter(VariableDescriptionPart1 %in% c("Real estate","Farm sector debt","Non-real estate"))

debt$variable <- paste(debt$VariableDescriptionPart1, debt$VariableDescriptionPart2, sep="_")

debt <- debt[c(1,2,6,8:9)]
unique(debt$variable)

debt <- debt %>% mutate(REAL_GDP = Amount / (ChainType_GDP_Deflator/100))

debt_tidy <- debt %>% pivot_wider(names_from = variable, values_from = Amount)

```

Okay, how do we use this GDP deflator? I am pretty sure this is correct (though, I am taking authority from kahn academy... so... https://www.khanacademy.org/economics-finance-domain/ap-macroeconomics/economic-iondicators-and-the-business-cycle/real-vs-nominal-gdp/v/example-calculating-real-gdp-with-a-deflator):

nominal/real = deflator/100

# plot debt
```{r}

# Nominal debt
debt %>%
  filter(variable %in% c("Real estate_All","Farm sector debt_All","Non-real estate_All"),
         Year >= 1960) %>%
ggplot(.) +
  geom_line(aes(x = Year, y = Amount*1000, color = variable), alpha = 0.8) +
  theme_bw() +
  scale_color_manual(labels = c("Farm sector", "Non-real estate", "Real estate"), values = c("red", "blue","green4")) +
  labs(title = "US Farm Debt", color = "Debt Type", y = "Nominal Dollars") +
    scale_y_continuous(breaks=c(100000000000,200000000000,300000000000,400000000000),
        labels=c("$100B", "$200B", "$300B","$400B")) +
  theme(legend.position="bottom") +
  ggsave('./viz/debt.jpeg', width = 6, height = 4, dpi = 300)

# Real debt
debt %>%
  filter(variable %in% c("Real estate_All","Farm sector debt_All","Non-real estate_All"),
         Year >= 1960) %>%
ggplot(.) +
  geom_line(aes(x = Year, y = REAL_GDP*1000, color = variable), alpha = 0.8) +
  theme_bw() +
  scale_color_manual(labels = c("Farm sector", "Non-real estate", "Real estate"), values = c("red", "blue","green4")) +
  labs(title = "US Farm Debt", color = "Debt Type", y = "Real US Dollars") +
  scale_y_continuous(breaks=c(100000000000,200000000000,300000000000,400000000000),
        labels=c("$100B", "$200B", "$300B","$400B")) +
  theme(legend.position="bottom") +
  ggsave('./viz/debt-real.jpeg', width = 6, height = 4, dpi = 300)
```

# Real estate debt by lender/holder
```{r}
library(scales)
viridis(7, option = "A")

debt %>%
  filter(variable %in% c("Real estate_Commercial banks","Real estate_CCC storage and drying loans","Real estate_Farm Credit System","Real estate_Farm Service Agency","Real estate_Farmer Mac","Real estate_Individuals and others","Real estate_Life insurance companies"),
         Year >= 1960) %>%
ggplot(.) +
  geom_line(aes(x = Year, y = REAL_GDP*1000, color = variable), alpha = 0.8) +
  theme_bw() +
  scale_color_manual(labels = c("CCC Loans", "Commercial Banks", "Farm Credit System","Farm Service Agency","Farmer Mac","Individuals & Others", "Life Insurance"), values = c("#000004FF", "#2D1160FF", "#721F81FF", "#B63679FF", "#F1605DFF", "#FEAF77FF", "#FCFDBFFF")) +
  labs(title = "", color = "Debt Type", y = "Real US Dollars") +
  scale_y_continuous(breaks=c(50000000000,100000000000),
        labels=c("$50B", "$100B")) +
  theme(legend.position="bottom") +
  ggsave('./viz/debt-realestate-real.jpeg', width = 7, height = 4, dpi = 300)

debt %>%
  filter(variable %in% c("Real estate_Commercial banks","Real estate_CCC storage and drying loans","Real estate_Farm Credit System","Real estate_Farm Service Agency","Real estate_Farmer Mac","Real estate_Individuals and others","Real estate_Life insurance companies"),
         Year >= 1960) %>%
ggplot(.) +
    geom_bar(aes(fill=variable, y=REAL_GDP*1000, x=Year), position="stack", stat="identity") +
    scale_fill_viridis(discrete = T, option = "magma",labels = c("CCC Loans", "Commercial Banks", "Farm Credit System","Farm Service Agency","Farmer Mac","Individuals & Others", "Life Insurance"),name="Holder") +
    theme_bw() +
  #scale_fill_discrete(labels = c("CCC Loans", "Commercial Banks", "Farm Credit System","Farm Service Agency","Farmer Mac","Individuals & Others", "Life Insurance"), values = c("#000004FF", "#2D1160FF", "#721F81FF", "#B63679FF", "#F1605DFF", "#FEAF77FF", "#FCFDBFFF")) +
    xlab("") +
  labs(title = "", y = "Real US Dollars") +
  scale_y_continuous(breaks=c(100000000000,200000000000,300000000000),
        labels=c("$100B","$200B","$300B")) +
  theme(legend.position="bottom") +
  ggsave('./viz/debt-realestate-propreal.jpeg', width = 7, height = 4, dpi = 300) +
    theme(legend.position="bottom") + guides(fill = guide_legend(nrow = 2))
```

# Non-real estate debt by lender/holder
```{r}
viridis(4, option = "D")

debt %>%
  filter(variable %in% c("Non-real estate_Farm Credit System","Non-real estate_Farm Service Agency","Non-real estate_Individuals and others","Non-real estate_Commerical banks"),
         Year >= 1960) %>%
ggplot(.) +
  geom_line(aes(x = Year, y = REAL_GDP*1000, color = variable), alpha = 0.8) +
  theme_bw() +
  labs(title = "Non-real Estate Debt: By holder") +
    scale_color_manual(labels = c("Farm Credit System","Farm Service Agency","Individuals & Others", "Commercial Banks"), values = c("#440154FF", "#31688EFF", "#35B779FF", "#FDE725FF")) +
  labs(title = "", color = "Holder", y = "Real US Dollars") +
  scale_y_continuous(breaks=c(25000000000,50000000000,75000000000),
        labels=c("$25B", "$50B","$75B")) +
  theme(legend.position="bottom") + 
  ggsave('./viz/debt-nonrealestate-real.jpeg', width = 7, height = 4, dpi = 300)

# Small multiple
debt %>%
  filter(variable %in% c("Non-real estate_Farm Credit System","Non-real estate_Farm Service Agency","Non-real estate_Individuals and others","Non-real estate_Commerical banks"),
         Year >= 1960) %>%
ggplot(.) +
    geom_bar(aes(fill=variable, y=REAL_GDP*1000, x=Year), position="stack", stat="identity") +
    scale_fill_viridis(discrete = T, labels = c("Farm Credit System","Farm Service Agency","Individuals & Others", "Commercial Banks"), name = "Holder") +
    ggtitle("Proportion of Non-real Estate Debt: By holder") +
    theme_bw() +
  labs(title = "", y = "Real US Dollars") +
  scale_y_continuous(breaks=c(50000000000,100000000000,150000000000,200000000000),
        labels=c("$50B","$100B","$150B","$200B")) +
  theme(legend.position="bottom") + 
  ggsave('./viz/debt-nonrealestate-propreal.jpeg', width = 7, height = 4, dpi = 300)
```

